<?php

/**
 * @file
 * Contains ps_general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function ps_general_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ps_general module.
    case 'help.page.ps_general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Perlita shop general module which contains settings.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ps_general_theme() {
  $templates = [];

  $templates['paragraph__shop_view'] = [
    'base hook' => 'paragraph',
    'file' => 'includes/theme.inc',
  ];

  return $templates;
}

/**
 * Implements hook_theme_suggestions_hook_alter().
 */
function ps_general_theme_suggestions_paragraph_alter(&$suggestions, $variables) {
  $entity = $variables['elements']['#paragraph'];
  $type = $entity->getType();

  if ($type == 'shop_view') {
    $suggestions[] = 'paragraph__shop_view';
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function ps_general_preprocess_commerce_product__product_overview(&$variables) {
  if (isset($variables['elements']['field_slika'][0]['#item'])) {
      if ($image = $variables['elements']['field_slika'][0]['#item']) {
          $file = File::load($image->target_id);
          $variables['image'] = [
              'url' => file_create_url($file->url()),
              'alt' => $image->alt,
          ];
      }
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function ps_general_preprocess_node__article__teaser(&$variables) {
  if ($image = $variables['elements']['field_preview_image'][0]['#item']) {
    $file = File::load($image->target_id);
    $variables['image'] = [
      'url' => file_create_url($file->url()),
      'alt' => $image->alt,
    ];
  }
}
