module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_log: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_promotion: 0
  commerce_shipping: 0
  commerce_store: 0
  commerce_tax: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  entity_reference_revisions: 0
  eu_cookie_compliance: 0
  facets: 0
  facets_range_widget: 0
  facets_rest: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  mailsystem: 0
  media_entity: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  path: 0
  physical: 0
  profile: 0
  ps_footer: 0
  ps_general: 0
  ps_landing_page_components: 0
  ps_main_menu: 0
  quickedit: 0
  rdf: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  social_auth_facebook: 0
  social_auth_google: 0
  social_auth_twitter: 0
  state_machine: 0
  super_login: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_xdebug: 0
  update: 0
  user: 0
  user_registrationpassword: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  perlita_shop: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: sl
