api_key: e3e250d1efa141472941a91ee0edd963-us18
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
langcode: sl
enable_connected: true
connected_id: null
connected_paths: null
