facebook: 'https://www.facebook.com/'
twitter: ''
google-plus: 'https://plus.google.com/discover'
linkedin: 'https://www.linkedin.com/uas/login'
instagram: 'https://www.instagram.com/?hl=en'
langcode: sl
