auth:
  social_auth_facebook:
    route: social_auth_facebook.redirect_to_fb
    img_path: modules/contrib/social_auth_facebook/img/facebook_logo.svg
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/contrib/social_auth_google/img/google_logo.svg
  social_auth_twitter:
    route: social_auth_twitter.redirect_to_twitter
    img_path: modules/contrib/social_auth_twitter/img/twitter_logo.svg
post_login: /user
redirect_user_form: false
disable_admin_login: true
disabled_roles: {  }
_core:
  default_config_hash: 1tS3jCuYxV3TXQ2cq320XarjdXWprvWK5bru8DCsIUY
langcode: sl
