super_login:
  login_text: Email
  forgot_pw_text: 'Ste pozabili geslo?'
  capslock_msg: 'Caps Lock On'
  new_account_text: 'Ustvari nov račun'
  login_title: ''
  password_reset_title: 'Ponastavitev gesla'
  back_link: 'Skoči nazaj na prijavo'
  messages: 0
  css: 0
  button_theme: 0
  placeholder: 0
  login_type: '1'
  capslock: 0
  login_placeholder: ''
  pass_placeholder: ''
_core:
  default_config_hash: LmPnyWGjnerstvvV_7kuxofM0TCr_46oT3YaWy9HYJs
langcode: sl
