display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ponastavi
      fields:
        placed:
          label: Datum
      arguments:
        uid:
          exception:
            title: Vsi
