display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ponastavi
      fields:
        media_bulk_form:
          action_title: Akcija
        uid:
          label: Avtor
        status:
          label: Stanje
          settings:
            format_custom_true: Objavljeno
        changed:
          label: Posodobljeno
        operations:
          label: Operacije
      filters:
        status:
          group_info:
            group_items:
              1:
                title: Objavljeno
        langcode:
          expose:
            label: Jezik
      empty:
        area_text_custom:
          content: 'Na voljo ni nobene vsebine.'
