label: profili
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Ponastavi
      arguments:
        uid:
          exception:
            title: Vsi
        type:
          exception:
            title: Vsi
        status:
          exception:
            title: Vsi
      title: profili
